repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix, lf]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.3'
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: unit-tests-suite
        name: unit-tests-suite
        description: Runs test suites
        entry: bin/test
        language: script
      #- id: build
      #  name: build
      #  description: Runs fresh build
      #  entry: bin/build
      #  language: script
